export default {
  pharmacy: "medical-bag",
  hospital: "hospital-marker",
  healthcentre: "hospital-box",
  school: "book-open-variant",
  college: "school-outline",
  university: "school",
  library: "bookshelf",
  newsagent: "newspaper-variant",
  supermarket: "basket",
  butchers: "food-drumstick",
  bakery: "bread-slice",
  sportscentre: "tennis-ball",
  park: "tree-outline",
  swimmingpool: "swim",
  railstation: "train-variant",
  busstation: "bus",
  other: "map-marker-question",
  phone: "cellphone-sound",
  email: "email",
  web: "web",
};
